server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /home/latex;

    # Nome do PDF gerado pela compilação de Feathertheme.tex
    index Feathertheme.pdf;

    location / {
        try_files $uri $uri/ =404;
    }
}
